[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}\n
{% for commit in commits %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/xeonixo/goup/commit/{{ commit.id }}))\
{% endfor %}
{% endfor %}\n
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "^[Ff]eat", group = "Features" },
  { message = "^[Ff]ix", group = "Bug Fixes" },
  { message = "^[Pp]erf", group = "Performance" },
  { message = "^[Rr]efactor", group = "Refactoring" },
  { message = "^[Rr]efractor", group = "Refactoring" },
  { message = "^[Dd]ocs", group = "Documentation" },
  { message = "^[Cc]hore", skip = true },
  { message = "^[Cc]i", skip = true },
  { message = "^[Ss]tyle", skip = true },
  { message = "^[Tt]est", skip = true },
  { message = ".*", group = "Changes" },
]
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "oldest"
